# Multi-Robot Coordination System Configuration

# System-wide coordination parameters
coordination:
  max_robots: 50
  heartbeat_interval: 1.0  # seconds
  task_timeout: 30.0  # seconds
  coordination_mode: "distributed"  # centralized, distributed, hybrid
  enable_dynamic_reconfiguration: true

# Learning algorithm parameters
learning:
  algorithm: "q_learning"  # q_learning, sarsa, actor_critic
  learning_rate: 0.01
  discount_factor: 0.95
  exploration_rate: 0.15
  exploration_decay: 0.995
  min_exploration_rate: 0.01
  update_frequency: 10  # updates per second
  convergence_threshold: 0.01
  enable_experience_replay: true
  replay_buffer_size: 10000

# Auction algorithm parameters
auction:
  timeout: 5.0  # seconds
  min_bid: 0.1
  max_iterations: 50
  price_increment: 0.05
  convergence_threshold: 0.01
  enable_multi_round_bidding: true
  bid_update_interval: 0.5

# Communication settings
communication:
  protocol: "ros2"  # ros2, mqtt, tcp, udp
  port: 11311
  buffer_size: 1024
  compression: true
  encryption: false
  max_retries: 3
  timeout: 5.0
  quality_of_service:
    reliability: "reliable"  # reliable, best_effort
    durability: "transient_local"  # volatile, transient_local, persistent
    history: "keep_last"  # keep_all, keep_last
    depth: 10

# Fault tolerance configuration
fault_tolerance:
  enable_fault_detection: true
  health_check_interval: 2.0  # seconds
  max_retries: 3
  failover_threshold: 2.0  # seconds
  failover_timeout: 2.0  # target failover time
  availability_target: 0.999  # 99.9%
  enable_predictive_maintenance: true
  fault_prediction_window: 300.0  # seconds
  
  # Recovery strategies
  recovery_strategies:
    communication_failure:
      - "restart_communication_module"
      - "switch_communication_channel"
      - "use_backup_communication"
      - "enter_autonomous_mode"
    
    hardware_failure:
      - "isolate_faulty_component"
      - "activate_backup_system"
      - "request_maintenance"
      - "graceful_shutdown"
    
    software_crash:
      - "restart_software"
      - "load_backup_configuration"
      - "reset_to_safe_state"
      - "emergency_shutdown"

# Performance monitoring
monitoring:
  enable_metrics_collection: true
  metrics_interval: 30.0  # seconds
  log_level: "INFO"  # DEBUG, INFO, WARNING, ERROR, CRITICAL
  enable_performance_profiling: true
  max_log_file_size: "100MB"
  log_rotation_count: 5
  
  # Key performance indicators
  kpis:
    target_efficiency: 0.92
    target_allocation_time: 50  # milliseconds
    target_communication_latency: 25  # milliseconds
    target_convergence_rate: 0.92
    target_policy_gradient: 0.85

# Security settings
security:
  enable_authentication: false
  enable_encryption: false
  certificate_path: "/etc/ssl/certs/robot_coord.pem"
  private_key_path: "/etc/ssl/private/robot_coord.key"
  trusted_robots: []  # list of trusted robot IDs
  security_level: "low"  # low, medium, high

# Environment settings
environment:
  type: "warehouse"  # warehouse, outdoor, factory, hospital
  boundaries:
    x_min: -100.0
    x_max: 100.0
    y_min: -100.0
    y_max: 100.0
    z_min: 0.0
    z_max: 3.0
  
  obstacles: []  # list of static obstacles
  
  charging_stations:
    - id: "cs_01"
      position: [0.0, 0.0]
      capacity: 5
    - id: "cs_02"
      position: [50.0, 50.0]
      capacity: 3

# Task management
task_management:
  max_pending_tasks: 100
  task_priority_levels: 5
  enable_task_preemption: true
  task_allocation_strategy: "auction"  # auction, greedy, random, optimized
  enable_task_decomposition: true
  min_task_execution_time: 1.0  # seconds
  max_task_execution_time: 600.0  # seconds

# Robot constraints
robot_constraints:
  max_velocity: 2.0  # m/s
  max_acceleration: 1.0  # m/s²
  max_battery_capacity: 100.0  # percentage
  min_operating_battery: 15.0  # percentage
  communication_range: 50.0  # meters
  sensor_range: 10.0  # meters
  payload_capacity: 10.0  # kg

# Simulation settings (for testing)
simulation:
  enable_simulation_mode: false
  real_time_factor: 1.0
  random_seed: 42
  enable_noise: true
  noise_parameters:
    position_noise: 0.01  # meters
    sensor_noise: 0.05
    communication_noise: 0.02
  
  # Virtual robot settings
  virtual_robots:
    count: 5
    spawn_area:
      x_range: [-10.0, 10.0]
      y_range: [-10.0, 10.0]
    capabilities:
      - ["navigation", "sensing"]
      - ["manipulation", "navigation"]
      - ["sensing", "analysis"]
      - ["navigation", "manipulation", "sensing"]

# Database configuration
database:
  enable_database: false
  type: "sqlite"  # sqlite, postgresql, mongodb
  connection_string: "sqlite:///multi_robot_coordination.db"
  enable_task_logging: true
  enable_performance_logging: true
  enable_fault_logging: true
  log_retention_days: 30

# Web interface configuration
web_interface:
  enable_web_interface: true
  port: 8080
  host: "0.0.0.0"
  enable_authentication: false
  enable_real_time_updates: true
  update_frequency: 2.0  # seconds

# API configuration
api:
  enable_rest_api: true
  port: 8081
  host: "0.0.0.0"
  enable_cors: true
  rate_limiting:
    requests_per_minute: 100
    burst_size: 20

# Advanced features
advanced:
  enable_machine_learning: true
  enable_predictive_analytics: true
  enable_swarm_intelligence: false
  enable_blockchain_consensus: false
  enable_edge_computing: false
  
  # Machine learning settings
  ml_settings:
    model_update_frequency: 300.0  # seconds
    training_data_retention: 7  # days
    enable_online_learning: true
    enable_transfer_learning: false
    
  # Optimization settings
  optimization:
    enable_genetic_algorithm: false
    enable_particle_swarm: false
    enable_simulated_annealing: false
    optimization_frequency: 3600.0  # seconds

# Development and debugging
development:
  enable_debug_mode: false
  enable_verbose_logging: false
  enable_profiling: false
  enable_memory_monitoring: false
  enable_cpu_monitoring: false
  
  # Testing settings
  testing:
    enable_unit_tests: true
    enable_integration_tests: true
    enable_performance_tests: true
    test_data_path: "test_data/"
    benchmark_duration: 300.0  # seconds

# Backup and recovery
backup:
  enable_automatic_backup: true
  backup_interval: 3600.0  # seconds
  backup_location: "/var/backups/multi_robot/"
  backup_retention_days: 7
  enable_incremental_backup: true
  
  # Recovery settings
  recovery:
    enable_automatic_recovery: true
    recovery_timeout: 60.0  # seconds
    max_recovery_attempts: 3
